### ISSUE TITLE
ClassLoader Error `sbt run`

### ISSUE THREAD

**Issue by Jentsch** [leanovate/slick-spatial#1]
I got a exception on starting the project with `sbt run` / `activator run`. However `sbt start` works fine. Seems to be a class loader problem.

Exception:

! @6meaj8i49 - Internal server error, for (GET) [/] ->

@6meaj8i49: Execution exception in /home/[...]/slick-jts/app/controllers/Application.scala:55
        at play.api.Application$class.handleError(Application.scala:296)
        at play.api.DefaultApplication.handleError(Application.scala:402)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215)
        at scala.util.Try$.apply(Try.scala:191)
        at scala.util.Failure.recover(Try.scala:215)
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: Allgemeiner Fehler: "java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/CoordinateSequenceFilter"
General error: "java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/CoordinateSequenceFilter"; SQL statement:
INSERT INTO SHAPES (id, district_name, shape) VALUES (?, ?, ?); [50000-186]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.message.DbException.convert(DbException.java:291)
        at org.h2.command.Command.executeUpdate(Command.java:262)
        at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:198)
        at com.jolbox.bonecp.PreparedStatementHandle.execute(PreparedStatementHandle.java:140)
        at controllers.Application$$anonfun$populateDB$1.apply(Application.scala:55)
        at controllers.Application$$anonfun$populateDB$1.apply(Application.scala:46)
        at play.api.db.DBApi$class.withConnection(DB.scala:81)
        at play.api.db.BoneCPApi.withConnection(DB.scala:267)
        at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:162)
        at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:162)
        at scala.Option.map(Option.scala:146)
        at play.api.db.DB$.withConnection(DB.scala:162)
        at controllers.Application$.populateDB(Application.scala:46)
        at controllers.Application$$anonfun$setup$1.apply(Application.scala:22)
        at controllers.Application$$anonfun$setup$1.apply(Application.scala:21)
        at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464)
        at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464)
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433)
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432)
        at play.api.mvc.Action$.invokeBlock(Action.scala:556)
        at play.api.mvc.Action$.invokeBlock(Action.scala:555)
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
        at scala.Option.map(Option.scala:146)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
        at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
        at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        ... 6 more
Caused by: java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/CoordinateSequenceFilter
        at org.h2.value.Value.convertTo(Value.java:818)
        at org.h2.table.Column.convert(Column.java:148)
        at org.h2.command.dml.Insert.insertRows(Insert.java:143)
        at org.h2.command.dml.Insert.update(Insert.java:114)
        at org.h2.command.CommandContainer.update(CommandContainer.java:78)
        at org.h2.command.Command.executeUpdate(Command.java:254)
        ... 38 more
Caused by: java.lang.ClassNotFoundException: com.vividsolutions.jts.geom.CoordinateSequenceFilter
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 44 more

**Comment by falsewasnottrue** [comment]
In Dev mode, h2 runs with its own class loader
CommonClassLoader must have access to all necessary jars for spatial extension.

cf. https://groups.google.com/forum/#!topic/play-framework/Efh1am71XtA
